#############################
#        TO FILL            #
#############################

# The title that appears on the tab
title: Slow the Spread / Flatten The Curve

# The title on the web page
full_name: Eric Stiens

# The type of layout
# Options: ROWS, SQUARES, COLUMNS
layout_style: ROWS

# Variables below are default. Feel free to customize the values below, but do
# not remove the property.

# Integer: Spacing between each photo
spacing: 10

# Boolean(true|false): Shuffle the photos in the album
shuffle: false

# Integer: Number of columns for square or columns
columns: 4

# Integer: Max height for rows
max_height: 400

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl: /

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
# url: http://andyzhang.net/gallery
